name: Home Manager
main: com.github.SaxSalute.HomeManager.HomeManager
version: 1

commands:
    createhome:
        description: Saves the selected area as an available home
        usage: /createhome [name of home]
        permission: HomeManager.createhome
        permission-message: You don't have <permission>
    listhomes:
        description: lists all homes and their owners
        usage: /listhomes
        permission: HomeManager.listhomes
        permission-message: You don't have <permission>